[workspace]
members = ["crates/houjing-bezier", "crates/houjing-main", "crates/experiments/*"]
resolver = "2"

[profile.dev]
debug = 0
strip = "debuginfo"
opt-level = 0
lto = "thin"
incremental = true

[profile.dev.package."*"]
opt-level = 3