[package]
name = "houjing-bezier"
version = "0.0.1"
edition = "2021"

[dependencies]
# parse and export
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# fit
nalgebra = "0.32.3"
rand = "0.8.5"
rand_distr = "0.4.3"

[dev-dependencies]
# For testing
approx = "0.5" 